---

name: Tests

on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - run: pip install flake8 flake8-import-order
      - run: flake8 .
      - run: python -m unittest discover tests
